name: Telegram Bot

on:
  workflow_dispatch:
  push:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install requirements
        run: |
          pip install python-telegram-bot

      - name: Run bot
        run: |
          python main.py
